[features]
seeds = false
[programs.localnet]
carbon = "FLihr2MTD514e7hSHXAs2vu9t9i4KszsZ6SNz8jK6q1g"

[test]
startup_wait = 30000
[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "tests/accounts/USDC.json"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
dump = "yarn run ts-node scripts/dump.ts"
test = "yarn run ts-mocha -p ./tsconfig.json --no-timeouts -s 0 tests/**/*.ts"
